### PR TITLE
Adding ImageX values to the Fatjet table

### PR DESCRIPTION
**Pull request by knash**
#### PR description:

Adds the image taggers to the Fatjet table for use with B2G/EXO analyses (for example, B2G-20-002).  Description of the algorithm and relevant comparisons can be found in JME-18-002. 

The training .pb files are stored in NanoAOD/data although perhaps these will need to be transferred over to https://github.com/cms-nanoAOD/PhysicsTools-NanoAOD?

The subjet collection needs to be updated to add additional b-tag values.  This is performed in nano_cff.py along with the other updateJetCollection calls.  The subjet table should remain unchanged.

The producer is added to plugins and called in jets_cff after updatedJetsAK8WithUserData and before finaljetsAK8.   This PR should not change any event content outside of the added Fatjet floats.

@pmaksim1 @clelange

### CODE REVIEW

**Comment by pmaksim1** [comment]
Hi @peruzzim @fgolf, any news on integrating this?  We in B2G would *really* like to get these variables into v8.  (Ideally, we should have had them in v7, but we barely missed that.)

Our late spring/summer analyses depend on some of these jet taggers, so if we don't get them now, their schedule may slip :-/

Many thanks!

**Comment by clelange** [comment]
The error message doesn't seem to be related to the PR (https://gitlab.cern.ch/cms-nanoAOD/nanoAOD-integration/-/jobs/7213211#L3689):

```shell
Exception Message:
A std::exception was thrown.
no method or data member named "stage1_2_cat_pTjet25GeV" found for type "HTXS::HiggsClassification"
```

Any advice how to proceed?

**Comment by knash** [comment]
@clelange yeah, this. is something I saw during testing.
It is unrelated to my scripts -- due to the HTXS 1.2 code:
https://twiki.cern.ch/twiki/bin/view/CMSPublic/WorkBookNanoAOD#Recipe_for_the_current_HEAD_of_N

**Comment by peruzzim** [comment]
debugging the validation area... it should not happen there...

**Comment by peruzzim** [comment]
I've now checked better the content of this PR.
This has to be integrated with the rest of taggers for AK8 jets in the JME packages, via a separate PR to the upstream repository, and then simply run and read during NanoAOD production, as we do e.g. for DeepAK8.
I refer in particular to the content of the `PhysicsTools/NanoAOD/plugins/ImageProducer.cc` file, which is quite complex. Please do not include the NanoAOD modifications in this pull request that you will open.

For the future, after the above is done, I can already point you to some items to be modified in the NanoAOD part:

- identify some subset of the scores that are actually needed
- set an appropriate precision for them
- the `nanoAOD_addImageInfoAK8` function has to be integrated with the other ones, exactly as we do for e.g. DeepAK8 scores

**Comment by peruzzim** [comment]
For the moment, in view of the above, I close this PR. Please reopen when the functionality in CMSSW is ready.

**Comment by knash** [comment]
Hello, thank you for the comment but could you clarify a bit more?  
I just open a PR to PhysicsTools/NanoAOD/plugins but to the CMSSW Master?

I followed a few examples for this PR, but explicitly the LSF PR where the producer was added.  
https://github.com/cms-nanoAOD/cmssw/pull/484
This should be exactly analogous, and will only be run in NanoAOD.

**Comment by peruzzim** [comment]
While conceptually having the same outcome (calculate a variable for a fat jet and store it), technically the complexity is very different in the nature of the code, usage of other packages, and meaning of the output. This is not just a simple variable matching fat jet with electron or muon content, but rather a full-fledged tagger. It should be treated exactly as e.g. DeepAK8, DeepDoubleX and similar - which means, integrated in the proper place.

**Comment by knash** [comment]
Hello, no not conceptually.  

The LSF takes a pfcandidate loop as input into a discriminator then outputs a variable to be used on AK8 jets.  This variable is absolutely a full blown tagger, it is used for H->WW* etc -- there is really no difference. 

DeepAK8/DeepDoubleX are run in analogy to b tagging, which doesn't really make sense here -- this is explicitly to be run after b tagging.  

I do not see an argument for complexity, but the space footprint and processing time requirements are relevant --  can we check to see if these are ok and that there is no content change to other nanoAOD branches?

**Comment by knash** [comment]
I still have not received an answer to my question though.  
Where exactly does the producer go?  It is a NanoAOD plugin that inexplicably does not go into NanoAOD/plugins.

So where do I put it?

**Comment by knash** [comment]
@gershtein @pmaksim1 @clelange @peruzzim

**Comment by peruzzim** [comment]
the integration of this feature, and others of similar type, is currently on hold pending discussions with conveners and other people in different fora. please stand by for the moment, will let you know about how to proceed with development.

**Comment by knash** [comment]
Hello, it has been some time now without correspondence.  I think what would make the most sense for us would be to open this PR back up, check for processing time and space requirements etc, and then merge.

**Comment by knash** [comment]
Hello, so what was the outcome here?  Can we re-open this or do I need to make a new PR?

**Pull request closed without merging**
