### PR TITLE
Solve bugs in lepton matching for Tau_genPartFlav [102X]

### PR DESCRIPTION
**Pull request by IzaakWN**
Please see 
https://github.com/cms-nanoAOD/nanoAOD-tools/issues/124#issuecomment-472415857

### CODE REVIEW

**Comment by IzaakWN** [comment]
It seems the compilation has failed because `GenParticle::isPrompt` does not exist. Judging from this line, maybe `statusFlags().isPrompt()` should work? Or should we add this function here somewhere:
https://github.com/cms-sw/cmssw/blob/master/DataFormats/HepMCCandidate/interface/GenParticle.h#L54

**Comment by arizzi** [comment]
yes it should.. can you test locally first?

**Comment by IzaakWN** [comment]
Can you try again, please?

**Comment by steggema** [comment]
Triggered by @peruzzim's response here https://github.com/cms-sw/cmssw/issues/26163#issuecomment-481176557: This change is in line with our Tau POG request. What prevents this from being merged?

**Comment by peruzzim** [comment]
nothing I think - it's on track to be merged in this round

**Review by peruzzim — APPROVED** [review]
small changes in Tau_genPartFlav in MC, as expected

**Pull request merged**
