### PR TITLE
Adding a fine-tuned version of the 'betastar' kind of variables. Already presented in the main CMSSW.

### PR DESCRIPTION
**Pull request by errai-**
#### PR description:

All information and discussion can be found in the PR: https://github.com/cms-sw/cmssw/pull/26767

A conclusion was reached that for testing purposes, it would be better to present the PR here, first.

### CODE REVIEW

**Comment by errai-** [comment]
Could I have some human contact on this thread, as things do not seem to be progressing?

**Comment by peruzzim** [comment]
Sorry @errai-, I did not have the chance to follow up on this lately. It seems something bad happened with the history, could you please check that? If needed you can update the branch in place. Thanks!

**Comment by errai-** [comment]
@peruzzim, could you clarify what the issue is here? To me, only green lights & "no conflicts" are shown in this thread.

**Comment by peruzzim** [comment]
The issue is quite clear: the diff shows that this PR changes 18k files. Which release did you base your developments on?

**Comment by steggema** [comment]
@peruzzim @fgolf Maybe it helps to update https://github.com/cms-nanoAOD/cmssw to the latest central CMSSW?

**Comment by peruzzim** [comment]
@steggema the branches are now all updated, see details in #394, please cleanup and reopen as a new PR if needed

**Comment by peruzzim** [comment]
is this still relevant for the general NanoAOD, or only for the JME custom version?

**Comment by errai-** [comment]
Yes, this is still relevant. The PR got unfortunately delayed due to more pressing matters. I will return to this as soon as possible.

**Comment by errai-** [comment]
@peruzzim, the code editing has now been run (by scram b code-format), and the code may now be re-tested.

**Comment by errai-** [comment]
Hmm, my bad. Missed the dqm config update requirement. Now that should be ok & the description texts are a little better than before.

**Comment by errai-** [comment]
@peruzzim, it seems that everything should finally be ok, and as requested.

**Pull request merged**
