### PR TITLE
Add Supercluster energy storage for electrons

### PR DESCRIPTION
**Pull request by sethcooper**
#### PR description:

As per issue #457

### CODE REVIEW

**Comment by peruzzim** [comment]
this should be modified to store scE/E-1, so that the precision can be reduced, as for Ecorr (or do you prefer the transverse version? which one is used typically?)

**Comment by peruzzim** [comment]
@sethcooper please follow up on the comment above so we can integrate this in the next production

**Comment by sethcooper** [comment]
@peruzzim I've made the changes you've suggested.

**Comment by peruzzim** [comment]
I've fixed the fact that the recalibrated pt should be used - when available - to divide this quantity, otherwise one cannot go back to the exact SC Et from the NanoAOD content

**Pull request merged**
