### PR TITLE
Adding c-jet energy regression evaluation

### PR DESCRIPTION
**Pull request by andreypz**
#### PR description:

This PR runs c-jet energy regression evaluation. It stores two additional variables per/jet: energy correction and a resolution estimator.
This is a copy of b-jet regression setup. 
Corresponding issue is #429
 
#### PR validation:

This was validated in `CMSSW_10_2_16_UL` using ` cms-nanoAOD/master-102X` branch and following *temporary* instructions:
```
git cms-merge-topic 28095
git cms-merge-topic 28135
```
Then, the changes to the *jets_cff* file are copied to master branch.
 

It does not, because of:

> ImportError: No module named muonFSRProducer_cfi

I assume this will be fixed first, and then this PR would be applied.

### CODE REVIEW

**Comment by andreypz** [comment]
A patch to `nanoDQM_cfi.py` is done, please take a look.

**Comment by andreypz** [comment]
@gpetruc-bot 
This does not look right to me. The changes to nanoDQM related to this PR are implemented already...

**Comment by peruzzim** [comment]
please fix the conflict in jets_cff.py and update the DQM file without introducing the wrong amount of spaces at the end of the line, so that the script checking it will not complain

**Comment by andreypz** [comment]
I see... I was wondering what it complained about.
Fixed the spaces and conflict now.

**Comment by peruzzim** [comment]
@andreypz can you please run local tests and tell when the PR is ready to be tested? thanks

**Comment by andreypz** [comment]
Sorry, my fault. I thought it was an easy change and made it in the web interface. 
Apparently it did not show the proper diff after changes of b-jet regression stuff - a closing bracket was missing.

I checked it now locally. Hopefully it will work this time.

**Comment by andreypz** [comment]
Wait, no, it's not ready yet - the nanoDQM file got reversed again..
Don't know why... I'll fix it.

**Comment by andreypz** [comment]
Ok, please start the test again. I think it should pass now.

**Comment by peruzzim** [comment]
Technically it's ok. The size increase is not negligible, should be checked whether one can store these values with less precision - please do it (storing e.g. corr-1 that is a number close to zero).

In data there are strange double peak structures in DQM, in 80X and 94Xv1 (strangely not in 94Xv2 - please check the above links to dqm diff plots). Is this expected? Can you please check the input variables?

(tests configuration is here: https://gitlab.cern.ch/cms-nanoAOD/nanoAOD-integration/blob/master/scripts/run_test_long.sh)

**Comment by andreypz** [comment]
Alright, I now reduced the precision of **both b and c regression outputs** by 2. Is this going to help?
The impact on the values are less than 0.1% so it should be fine for both.
I did not want to change to `1-corr` because this would require change the analysis code as well, and also I don't really understand how that would allow to reduce precision...

As for the horn peaks - I don't know the reason for it now. We will investigate it after this is implemented in nanoAOD. In fact we do not have Data sample with this at the moment.
Also, I see that the DQM test is run on different data for different releases. That would also make a difference. The regression is trained on 2017 TTbar sample, so we don't expect it to perform well on 2016, but probably be OK for 2018. 
We will have separate training for 2016 and 2018 later.

**Pull request merged**
