### PR TITLE
Added HighPt info, puppiIsoId, softMvaScore

### PR DESCRIPTION
**Pull request by Fedespring**
#### PR description:
Muon variables are added: 
- refitted highPt: tunePmuonBestTrack->pt() as tunePpt/pt; 
- relative TrackerBased Isolation used in highPt analyses; 
- 3 working points for the puppiIsolation selector;   
- score variable for the softMvaId

#### PR validation:
runTheMatrix.py -l 10809.0 successfully completed 

Note that if you want to backport this PR to 10_2_X, you need to backport also the 
https://github.com/cms-sw/cmssw/pull/26233

### CODE REVIEW

**Comment by peruzzim** [comment]
I start testing this, but what will be the behaviour when running on MINIAOD produced in previous releases? The PUPPI selectors are not calculated there.
Has the `computePuppiCombinedIso` flag been implemented in `PATMuonUpdater`, that we use e.g. to recalculate miniIso in 80X?
The same question applies to tuneP estimates: will they give a sensible answer also when running on older releases?

**Comment by peruzzim** [comment]
`softMvaScore` is also empty in 80X and 94X (btw, please rename it to `softMva`): if not supported there, should be removed using modifiers + please update the DQM content using the patch provided as a basis, and setting correct ranges that cannot be autodetected

**Comment by Fedespring** [comment]
> I start testing this, but what will be the behaviour when running on MINIAOD produced in previous releases? The PUPPI selectors are not calculated there.
The puppi selectors are not present in the reco::Muon data format as you can see here
https://github.com/cms-sw/cmssw/pull/26233/files

> Has the `computePuppiCombinedIso` flag been implemented in `PATMuonUpdater`, that we use e.g. to recalculate miniIso in 80X?
No it is not.

> The same question applies to tuneP estimates: will they give a sensible answer also when running on older releases?
tuneP is fine in the older releases.

**Comment by peruzzim** [comment]
ok, then please remove them when using modifiers for old releases:

```
from ... import mod1
from ... import mod2
...
(mod1 | mod2 | mod3 | ...).toModify(muonTable, variableToRemove1 = None, variableToRemove2 = None)
``` 

the modifiers to be used are these ones
https://github.com/cms-nanoAOD/cmssw/blob/bd21613340dd666ba5348d1bc4678e321b927b7c/PhysicsTools/NanoAOD/python/nano_cff.py#L20-L24

**Comment by peruzzim** [comment]
@Fedespring no worries about DQM, I can fix it when merging

**Pull request merged**
