### PR TITLE
Added b-tag SF EDProducer to get event weights

### PR DESCRIPTION
**Pull request by mondalspandan**
This new addition does the following:

- Takes a jet collection as input (configurable, tested using linkedObjects-jets)
- Loads the BTagCalibration and Reader frameworks
- Reads SFs from a (configurable) .csv file with the systematics mentioned in the cff file
- Loops over jets for each event
- Accumulates product of SFs for jets that pass a configurable cut, for each event
- Adds a FlatTable containing the b-tagging event weight (product of SFs) to the output.

To test the code, I added some .csv files in a new "data" directory within the NanoAOD framework, and produced separate weight-tables for three different b-taggers configured with some test systematics (which can be found in the changes to the nano_cff.py file in the above github commit), but all of these could, of course, be changed later.

### CODE REVIEW

**Comment by arizzi** [comment]
can we make a single table producer with a vector or PSet  of taggers, filename, op, branchname in the config producing N different variables?

**Comment by arizzi** [comment]
the correct csv file for 2016 vs 2017 should be picked up based on era switches

**Comment by mondalspandan** [comment]
I incorporated the first comment. Now the producer takes vectors as input and produces one single table containing weights for multiple discriminators.

I shall look into the technical details for the SF .csv files of different eras and get back with the update soon.

**Comment by mondalspandan** [comment]
Hi Andrea, if I understand your second comment correctly, we wish to provide paths to SF .csv files for all eras and all discriminators in the config file, and the code needs to determine the MC campaign (Spring16, Summer16, Fall17, etc.) and then choose the relevant .csv files for that campaign automatically. I think this could be achieved with a PSet of weightFiles in the config and a series of if conditions in the producer. Could you point me to an example on how to determine the MC campaign name of the sample within a producer?

**Comment by arizzi** [comment]
not really automatically but with the era switch mechanism. see other cff files in NanoAod  for example, look for "toModify"

**Comment by mondalspandan** [comment]
If I understand correctly, some default configurations are defined in the bulk of the cff files, and whenever an era-based switch is required, one needs to call an era.toModify function and specify which of the default config variables need(s) to be redefined.

Could you let me know which era the default configs correspond to (i.e., the intended era if no toModify is defined)?

I also see that the current cffs are meant to support 80XLegacy and 92X. As I found out from the BTV conveners, current SFs are being derived for 94X (a list of supported campaigns are available in [the BtagRecommendation TWiki](https://twiki.cern.ch/twiki/bin/viewauth/CMS/BtagRecommendation)). In addition, cMVAv2 SFs will not be derived in 94X.

**Comment by arizzi** [comment]
I think you should put 2016 SF for 80X while  default should be for 2017 94X stuff.

**Comment by arizzi** [comment]
weights for 94X in today's talk at XPOG were clearly not having mean 1. Can you followup?

**Comment by mondalspandan** [comment]
Yeah, sure, I shall followup on this.

**Pull request merged**
