### PR TITLE
Update type-1 corrected PFMET with new JEC

### PR DESCRIPTION
**Pull request by ktht**
Issue described here: https://github.com/cms-nanoAOD/cmssw/issues/151
Code taken from here: https://twiki.cern.ch/twiki/bin/view/CMS/MissingETUncertaintyPrescription#PF_MET

In the current implementation, MET
https://github.com/cms-nanoAOD/cmssw/blob/0733e5e207804e946ba86b6ba60a27cac3dbf504/PhysicsTools/NanoAOD/python/met_cff.py#L20
is read from MINIAOD, which means that reapplying the JECs shouldn't change anything if we're using the same MC GT that was used in the MC production (e.g. 94X_mc2017_realistic_v10 for Fall17 campaign). This hypothesis turned out to be correct for `MET_pt`, (`MET_phi` obviously), `MET_sumEt` and `MET_covXY`, i.e. these values are reproducable (within 0.05%) if we use the original GT. But `MET_covXX` and `MET_covYY` (`MET_significance`) decreased (increased) consistently up to 10%. This may be expected if

- type-1 corrected MET is recomputed with the new JEC from raw MET which is stored in MINIAOD;
- the covariance matrix stored in MINIAOD is computed from the particles available in AOD;
- some (low-pT?) particles are dropped at MINIAOD production.

For this reason we may never fully recover the covariance matrix stored in MINIAOD even if we use the original JEC.

Of course, this is all just a guesswork (read: only explanation we have); maybe someone more knowledgeable could shed some light on this matter.

### CODE REVIEW

**Comment by arizzi** [comment]
so we better do not apply this when using same GT.. right?

**Comment by ktht** [comment]
Um.. yes, I guess so. But to me it's nontrivial to compare the GT that was used to produce the MINIAOD to the GT that's been provided by the user... Unless MINIAOD already stores the GT somewhere.

**Comment by arizzi** [comment]
in the provenance there is something like
ESSource: GlobalTag PAT
 parameters: {
  @module_edm_type: string tracked  = 'ESSource'
  @module_label: string tracked  = 'GlobalTag'
  @module_type: string tracked  = 'PoolDBESSource'
  connect: string tracked  = 'frontier://FrontierProd/CMS_CONDITIONS'
  globaltag: string tracked  = '101X_mcRun2_asymptotic_v2'
  snapshotTime: string tracked  = ''
  DBParameters: PSet tracked = ({
  })
  toGet: VPSet tracked = ({
  })
 }

**Comment by arizzi** [comment]
anyhow ... why should the met significance be different? all pfCands are store in miniaod and some uncertainties are available for all tracks down to pt = 0.5..
I think this should be reported to JETMET for further investigation, I'm guessing we can do much better than 10% discrepancy

**Comment by arizzi** [comment]
anyhow this need to be rebased because we updated the master removing the commits to the /data folder

**Comment by arizzi** [comment]
@ktht did you report this issue to JetMET?

**Comment by ktht** [comment]
Sorry, been busy lately. I just opened a thread in Missing ET forum.

**Comment by gpetruc** [comment]
Closing this PR, which is open since too long with no activity, and is now conflicting with the master branch.

**Pull request closed without merging**
