### PR TITLE
updating dimuon vertex for nanoAOD PR

### PR DESCRIPTION
**Pull request by gkaratha**
Dear all, 

This PR is a continuation from the [now closed]  #490 . A list with the changes I performed according to your comments:

1) Changed to final muons
2) Added the dimuon producer in nano_cfg
3) Pushed only my files without the other push

Tests:
1) Run on 500 evts of ttbar [*] with size increase of 0.5%. In that sample we find average pairs/evt of 0.21
2) Run on 100evts in DY [**] with size increase of 0.4%.  In that sample we find average pairs/evt of 0.4

Let me know if anything else is needed. Thanks.

Best regards,
George

[*]  /store/mc/RunIISummer16MiniAODv3/TTJets_DiLept_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/MINIAODSIM/PUMoriond17_94X_mcRun2_asymptotic_v3-v2/270000/5ABB0EC9-FCE9-E811-B517-0CC47A6C1056.root
[**] /store/mc/RunIIAutumn18MiniAOD/DYJetsToLL_M-50_Zpt-150toInf_TuneCP5_13TeV-madgraphMLM-pythia8/MINIAODSIM/102X_upgrade2018_realistic_v15-v1/60000/02BCC9C7-E0B2-B647-BEFB-71FB391741D7.root

### CODE REVIEW

**Comment by gkaratha** [comment]
Dear all,

Is this PR already merged? If not is there something that would you like to discuss on this PR or the code functionality? Thanks.

Best,
George

**Comment by peruzzim** [comment]
I'm afraid we need to descope this from the v7 production campaign

**Comment by gkaratha** [comment]
Hi Marco,

Ok sure. Is the delay because there is something wrong with the code or it is something irrelevant? I am not an expert but i see that passed the tests. Thanks.

Best regards,
George

**Comment by gkaratha** [comment]
Hi all,
Is this PR ok for you? Do i need to provide anything else? Thanks.

Best,
george

**Comment by gkaratha** [comment]
Dear all,

Is this PR ready to be merged? Any further actions required by my side?

Thanks,
George

**Comment by mariadalfonso** [comment]
closing this, as PRs are directly done in cmssw

**Pull request closed without merging**
