### PR TITLE
Split SimpleFlatTableProducer plugin into header and implementation

### PR DESCRIPTION
**Pull request by ktht**
This way a user can simply include the header file and define their own plugin based `SimpleFlatTableProducer` in a separate repository without the need of forking and editing the original plugin implementation.

Real-life example: I want to define
```cpp
typedef SimpleFlatTableProducer<reco::HTTTopJetTagInfo> SimpleHTTInfoFlatTableProducer;
```
but can only do that by editing `PhysicsTools/NanoAOD/plugins/SimpleFlatTableProducer.cc`. By pulling out the templates into a header file I can simply include the header in a completely different project without ever needing to edit any files in CMSSW repository.

### CODE REVIEW

**Review by peruzzim — CHANGES_REQUESTED** [review]
I find this splitting misleading. If you want to split the template class from its specialization (and maybe from its implementation), I think it should be done in separate files:
- SimpleFlatTableProducer.h + SimpleFlatTableProducer.cc -> template classes
- new file called SimpleCandidateFlatTableProducer.h (or cc?) -> specialization to reco::Candidate

**Comment by ktht** [comment]
I agree that the naming convention is a bit misleading. However, we can only split template classes and their specialization since the header must contain all the definitions of a template anyways.

The only question that still remains open (at least to me) is whether or not to make a separate .cc file per FWK module, i.e. should we

a) split everything:
* interface/SimpleFlatTableProducer.h -> template classes
* plugins/SimpleCandidateFlatTableProducer.cc
* plugins/SimpleGenEventFlatTableProducer.cc
* plugins/SimpleHTXSFlatTableProducer.cc

b) or keep all plugins in a single file:
* interface/SimpleFlatTableProducer.h -> template classes
* plugins/SimpleFlatTableProducer.cc -> all plugin implementations

I went for b), but I could rename the .cc file to something else (e.g. plugins/SimpleFlatTableProducerImpl.cc) for clarity. Or, do you prefer splitting everything as described in a)?

**Comment by peruzzim** [comment]
ok, then I would go with b) + renaming the file, thanks

**Comment by ktht** [comment]
Updated.

**Review by peruzzim — APPROVED** [review]

**Pull request merged**
