### PR TITLE
add the LHE particle four momenta

### PR DESCRIPTION
**Pull request by lenzip**
This PR addresses issue #129

### CODE REVIEW

**Comment by lenzip** [comment]
The use of this is to have the kinematics before the parton shower. I have changed the code to only save status 1 particles. The size increase now on ttbar is down to 2% (comparing 1000 event file sizes). If this is still to much, I have added a parameter to switch off the new behavior. In case we can switch it off by default, but it would still be useful to have the possibility save this additional information in case of need.

**Comment by gpetruc** [comment]
re-running the tests now.
another thing that in could be done to save space is to remove a few of the other LHE variables that are trivial to recompute from this new collection.

**Comment by lenzip** [comment]
Hi, failures seem to be related to file read errors.

**Comment by lenzip** [comment]
Hi Andrea,
     the main use is to re-weight Higgs signal samples to different 
spin/parity/width hypotheses with JHU/MELA.
This holds both for the signal at 125 and for the high mass signals.
The in HWW we also have EWK corrections to WW samples in the form of 
reweighting factors to be applied on top of the LHE level kinematics.
We may want to use this information to stitch samples with different gen 
level cuts (e.g. merge together WW+2jets and the dedicated high mjj sample).
So there are a few use cases. Clearly it is easier if the information is 
stored in all samples, but if its is too much, it would be already good 
to have the possibility to enable this behavior on demand.
So if you deem this to much I can switch if off by default and we do the 
samples that need this information privately.
Giulio

**Comment by peruzzim** [comment]
How many variables are needed to do the reweightings? Do you really need particle-level information or you might work with few event variables that are calculated in production (e.g. lheHT)?
In the latter case, I think one possibility would be to calculate those variables only in specific cases that can be triggered by the LHE header information or some other logic based on the event content, setting them to zero in all other samples (such that they can be compressed away).

**Comment by lenzip** [comment]
On 26/03/2018 11:31, peruzzim wrote:
>
> How many variables are needed to do the reweightings? Do you really 
> need particle-level information or you might work with few event 
> variables that are calculated in production (e.g. lheHT)?
>
No, the full 4 momenta are needed. I doubt we are the only ones needing 
them btw. I can dig the header for the signal samples at least and see 
if it can be switched on based on that.
Giulio

**Comment by amassiro** [comment]
If I may add, the EWK corrections we are referring to are for:
- WW
- WZ
- ZZ

If the increase of size is too much, maybe we can calculate the weights of the EWK corrections centrally in the production of the nanoAOD?
It will be a bit of "CPU", but then just one (or few) float to be saved, and it can be something all CMS can profit from, from SMP, to HIG, EXO, B2G ...

**Comment by arizzi** [comment]
a) we merge this now
b) we follow up (updating the existing issue) on possible ways to save space

**Comment by arizzi** [comment]
simply changing the base branch doesnt work I'll cherry pick this on the rebased branch -integration

**Pull request merged**
