### PR TITLE
DeepTauID to Nano at 102X

### PR DESCRIPTION
**Pull request by mbluj**
#### PR description:

This PR adds DeepTauID to NanoAOD for 102X. 

DeepTauID variables in tauTable are defined as in #27226 & #27227, but the DeepTauID is computed within the nanoAOD workflow (instead of being read from MiniAOD). This addition is **not active** for any of already defined NanoAOD eras, namely `run2_miniAOD_80XLegacy`, `run2_nanoAOD_94XMiniAODv1`, `run2_nanoAOD_94X2016`, `run2_nanoAOD_94XMiniAODv2`, `run2_nanoAOD_102Xv1`. Should it be protected by a dedicated era?

The PR is build on top of CMSSW_10_2_15_patch2 and contains DeepTau code as in (not yet merged) PR #27148.

#### PR validation:

Validated with nanoAOD workflow obtained with the following cmsDriver command which corresponds with NanoAODv5:
```
cmsDriver.py RunIIFall17NanoAODv5 --filein /store/mc/RunIIFall17MiniAODv2/TTToHadronic_TuneCP5_13TeV-powheg-pythia8/MINIAODSIM/PU2017_12Apr2018_94X_mc2017_realistic_v14-v1/40000/A256C80D-0943-E811-998E-7CD30AB0522C.root --fileout file:RunIIFall17NanoAODv5.root --mc --eventcontent NANOAODSIM --datatier NANOAODSIM --conditions auto:phase1_2017_realistic --step NANO --nThreads 2 --era Run2_2017,run2_nanoAOD_102Xv1 --no_exec -n 1000
```
as well as with its version without `run2_nanoAOD_102Xv1` era specifier.

The validation requires training files being part of cms-data/RecoTauTag-TrainingFiles#3, which can be alternatively got as follows:
```
git clone -b DeepTau2017v2 https://github.com/cms-tau-pog/RecoTauTag-TrainingFiles.git RecoTauTag/TrainingFiles/data
```

#### if this PR is a backport please specify the original PR:

This PR can be seen as expanded backport of #27226

### CODE REVIEW

**Comment by mbluj** [comment]
FYI, @steggema, @rmanzoni, @swozniewski, @roger-wolf

**Comment by mbluj** [comment]
Tests failed at compilation step. It is, as far as I can see, due to unrelated to this PR problem with Fireworks (missing `GL/glu.h` header).
```
>> Compiling  /builds/cms-nanoAOD/nanoAOD-integration/CMSSW_10_2_15/src/Fireworks/Vertices/src/TEveEllipsoidGL.cc 
In file included from /cvmfs/cms.cern.ch/slc7_amd64_gcc700/lcg/root/6.12.07-gnimlf5/include/TGLIncludes.h:21:0,
                 from /builds/cms-nanoAOD/nanoAOD-integration/CMSSW_10_2_15/src/Fireworks/Vertices/src/TEveEllipsoidGL.cc:17:
/cvmfs/cms.cern.ch/slc7_amd64_gcc700/lcg/root/6.12.07-gnimlf5/include/GL/glew.h:1141:10: fatal error: GL/glu.h: No such file or directory
 #include <GL/glu.h>
          ^~~~~~~~~~
compilation terminated.
gmake: *** [config/SCRAM/GMake/Makefile.rules:1673: tmp/slc7_amd64_gcc700/src/Fireworks/Vertices/src/FireworksVertices/TEveEllipsoidGL.cc.o] Error 1
```

**Comment by peruzzim** [comment]
let me retest on top of 10_2_16

**Comment by mbluj** [comment]
Due to some reasons 10_2_16 does not appear to be present on release list; you can try with 10_2_16_UL which looks be identical to 10_2_16 accordingly to release notes.

**Comment by peruzzim** [comment]
it seems there is a conflict with 10_2_16, please wait until the test is over and merged to master-102X, we will then fix this

**Comment by peruzzim** [comment]
@mbluj I have updated master-102X to 10_2_16_UL, could you please replace this PR with something built on top of what was already merged in CMSSW? (avoiding the current conflict, and complicated features in the history that would complicate porting to different branches) Thanks!

**Comment by mbluj** [comment]
OK. So I am closing this PR and will open new when ready.

**Comment by mbluj** [comment]
For reference: this PR is superseded by #388

**Pull request closed without merging**
