### PR TITLE
Nano aod tau trigger

### PR DESCRIPTION
**Pull request by tstreble**
This PR:
- adresses issue #73 (fix of L1 seed pT)
- adds various trigger filters to be used for tau triggers

### CODE REVIEW

**Comment by arizzi** [comment]
looking at the DQM plots, it seems for 80X we do not fill the L1 pt seed, can this be fixed by accessing the information in some other way ?

**Comment by tstreble** [comment]
I'll have a look and update accordingly
Thanks for noticing it

**Comment by arizzi** [comment]
ok let me know if you find a quick fix, otherwise we can merge  this and have a dedicated PR for that.

**Comment by arizzi** [comment]
let me merge this, anyhow the L1seed was zero also without this PR for 80X.

I need this fix in for the update of the PR against cmssw

**Pull request merged**
