### PR TITLE
Adding HTXS stage 1.2 to nanoAOD

### PR DESCRIPTION
**Pull request by adewit**
#### PR description:

This adds the stage 1.2 HTXS classification to nanoAOD. Note: only the last commit (79c4981)  is nanoAOD related - the others are the ones here: https://github.com/cms-sw/cmssw/pull/28444/commits just merged into CMSSW master.

I assume cms-nanoAOD/cmssw:master-cmsswmaster will be synched with cms-sw/cmssw:master at some point so that the diff will effectively just be 79c4981. 

#### PR validation:

Processed ggH events (102X miniAOD) and verified that the classification works as expected

#### if this PR is a backport please specify the original PR:

Not a backport

### CODE REVIEW

**Comment by peruzzim** [comment]
@adewit was the upstream PR rebased at some point? the commit hashes don't match.
could you please cherry-pick the last commit on top of 11_0_0 (or anything after the upstream PR was merged) and update this PR by force-pushing on the same branch, so we avoid duplicated history?

**Comment by adewit** [comment]
@peruzzim ah yes I hadn't taken all the various rebases into account :-( ok, have now updated the PR (though annoyingly there is now a merge commit in the history...)

**Comment by peruzzim** [comment]
no problem for the merge commit, thank you

**Comment by peruzzim** [comment]
re-testing with #28444 in the environment (was merged after upstream had been moved to 11_1_X)

**Pull request merged**
