### PR TITLE
Add Nano in some runTheMatrix workflows

### PR DESCRIPTION
**Pull request by arizzi**
it is not clear if this would spoil relval production.

to be discussed in cms-sw/cmssw#20626

### CODE REVIEW

**Comment by gpetruc** [comment]
136.788 is a workflow that includes re-HLT, so I think it's would make sense to include in the PR also also https://github.com/cms-nanoAOD/cmssw/commit/8069037bdaface102f425d1b92b1c063f5c18a97 (which was already in the matrix branch I told you), and pass the proper hlt process name to the nano step

**Comment by arizzi** [comment]
mhh I thought I cherrypicked it already but probably was in the wrong
branch... tomorrow

Il 04 ott 2017 10:06 PM, "Giovanni Petrucciani" <notifications@github.com>
ha scritto:

**Comment by arizzi** [comment]
I'm going to add more stuff in few minutes
I'll take that too

**Comment by arizzi** [comment]
the following would test production of NANO from existing samples
runTheMatrix.py -l '1325.6,1325.7,1325.8,1329.1'

plus some workflow in
runTheMatrix.py -l 'limited'

now have the NANOAOD production as last step (to be retested with recent changes)

**Comment by arizzi** [comment]
do not merge this, I'll reopen with some rebase to be able to submit the PR on cmssw

**Comment by arizzi** [comment]
in fact merging by hand seem to work... I'm nost sure what the effect of merging this would be on the mergability of master with #20905

**Comment by gpetruc** [comment]
NOTA BENE: Reminder: when we merge these, we should also update the scripts in [nanoAOD-integration](https://gitlab.cern.ch/cms-nanoAOD/nanoAOD-integration/tree/master/scripts) for the change in data tier (`NANO` &rarr; `NANOAOD[SIM]`) and for the merging using cmsDriver

**Comment by gpetruc** [comment]
uhm, now this is out of sync with the merged https://github.com/cms-sw/cmssw/pull/20905, maybe we can just close and wait for when we merge 940pre3 into master?

**Pull request closed without merging**
