### PR TITLE
Added non-PF track, ecal and hcal isolation within a cone of 0.3

### PR DESCRIPTION
**Pull request by olaiya**
Just 3 variables needed for UK exotic analyses that use non-PF electrons

### CODE REVIEW

**Comment by arizzi** [comment]
can you clarify a bit more on the usage of those variables and why you need those wrt PF based isolation information?

**Comment by olaiya** [comment]
These variables are useful for a few our analyses. We are using non-PF electrons. In some cases electrons within jets so no isolation required but also isolated electrons so we would need these variables. We would also like to look at modifications to high energy electrons which require these variables too.

**Comment by arizzi** [comment]
I'm afraid I'm not understanding. You are adding the detector based isolation variables for the electrons (doesn't matter if the electron is PF or non PF). Why do you want to use non-PF isolation variables instead of PF isolation variables (that are not specific of PF electron, they could be computed for any object)

**Comment by olaiya** [comment]
Our high energy electron selection uses non-PF isolation

**Comment by arizzi** [comment]
right, this I understood. I was asking above why you need non-PF based isolation. Do you have some AN/studies that show it being non optimal or is it an historical relic ?

**Comment by emanueledimarco** [comment]
Is this because of the [HEEP electron ID](https://twiki.cern.ch/twiki/bin/view/CMS/HEEPElectronIdentificationRun2) ?
In this case isn't sufficient to store the bit of the WP, as we are doing for the other cut based selections of egamma?

**Comment by olaiya** [comment]
Yes, it is because of HEEP ID and non-PF isolation is more optimal for our analysis. The bit of the WP is useful. However with the non-PF isolation variables we can then perform background studies too.

**Comment by arizzi** [comment]
we really need more information about what having this allows and why that is important to have on 10B events.
3 floats * N electrons  * size of (compressed) float could be as large as 1-2% of the total NanoAOD size, so we weight carefully what should be included and what should not.
Can you clarify what you mean with background studies here?

**Comment by olaiya** [comment]
In the Z' analysis we estimate the jet background by using the tracker isolation as a template. So we need to construct the id from its constituents. I hadn't envisaged and increase of 1-2%.  I would be happy to reduce the precision. Does this help at all?

**Comment by arizzi** [comment]
can't you use charged hadron isolations templates instead? Is there any specific reason to use tracks instead of pf charged hadrons?
I'm not understanding the second statement.
Reduced precision (2 bytes instead of 4 per float)  on 3 floats * 2 electrons is 12 bytes, i.e. ~1-1.5% of the total size.
Perhaps we can have a live chat to sort this out.

**Comment by olaiya** [comment]
I'm not an expert on calculating the jet background using the trk iso so can't really comment on using the pf charged hadrons instead. Yes, I think I live chat would be best.

**Comment by arizzi** [comment]
btw before we find a slot for a skype  call (likely next week) can you define a pt threshold for those electrons?
if this is meant for HEE, what if we store
"dr03EcalRecHitSumEt()*(pt>200)" i.e. 0 for all electrons with pt < 200 ?

**Comment by olaiya** [comment]
Our pt threshold is 35 GeV for electrons. We look at electron pairs so pt>200 will be a dramatic cut in the mass spectrum. A chat next week would be good. If there is some way to include the variables without such an increase in size that would be great.  I definitely don't want to push the file sizes up by up to 1.5%

**Comment by gpetruc** [comment]
considering that the HEEP wp will be added already as a bit (or a bitmask if it's more useful), then maybe you could do with just the tracker isolation and not also the other two?

**Comment by olaiya** [comment]
We would need to reconstruct HEEP in different trk iso windows in which the HEEP bit would not work. So we would need all the constituent HEEP variables. Does it help calculate these variables only for electrons with pt > 35? If we are finding the added size is still too large then maybe we will have to leave them out for now whilst I think about it again. These variables are useful but I am not going to argue they warrant a 1-1.5% increase in data size

**Comment by arizzi** [comment]
but a HEEP bitmask excluding the trk isolation plus the trk isolation value would be enough?

**Comment by olaiya** [comment]
I think so! I would need to check this fulfils our needs.

**Comment by arizzi** [comment]
reducing the precision and adding the pt cut should cut the size by half
i.e. something like:
`Var("?pt>35?dr03TkSumPt():0",float,doc="Non-PF track isolation within a delta R cone of 0.3",precision=8),`

but if we can work with bitmasks it would be even better

**Comment by olaiya** [comment]
That would be great if the pt cut could be implemented. I will speak to relevant people tomorrow about the bit mask and get back to you.

**Comment by arizzi** [comment]
for the pt please just update this PR adding the `?(pt>35)?` in the var definition

**Pull request merged**
