### PR TITLE
Add DeepMET into NanoAOD

### PR DESCRIPTION
**Pull request by yongbinfeng**
#### PR description:

The PR is to add DeepMETs into NanoAOD. Related issue: https://github.com/cms-nanoAOD/cmssw/issues/525. 

One quick overview for DeepMET from the February CMS Week: https://indico.cern.ch/event/883809/contributions/3733818/

The PR is based on the recent CMSSW master branch (11_2_X). Once the `master-cmsswmaster` here is synced with the `master` in central CMSSW, it should be much much cleaner. Otherwise could you please suggest a better way to implement this?

The Era customizations might be able to be optimized, if experts could provide help on: https://github.com/cms-nanoAOD/cmssw/issues/524

#### PR validation:

test on a small sample and it works as expected. Also passed unit tests and the runTheMatrix tests.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

not a backport.

@steggema @intrepid42

add JMET conveners: @ahinzmann @lathomas

### CODE REVIEW

**Comment by ahinzmann** [comment]
@yongbinfeng Would you maybe mind making the same PR to cms-sw master? This would make it much more readable and reviewable, while the cms-nanoAOD is out of sync?

**Comment by yongbinfeng** [comment]
@ahinzmann sure. happy to do it.

**Comment by mariadalfonso** [comment]
@yongbinfeng 
can you rebase this PR ?
and bring it in synch with the https://github.com/cms-sw/cmssw/pull/30291

**Comment by yongbinfeng** [comment]
> @yongbinfeng
> can you rebase this PR ?
> and bring it in synch with the [cms-sw#30291](https://github.com/cms-sw/cmssw/pull/30291)

@mariadalfonso done. Rebased to the `cms-nanoAOD:master-cmsswmaster` branch now.
And i assume it would always be in sync with https://github.com/cms-sw/cmssw/pull/30291, since the two PRs are from the same branch in my side?

**Comment by mariadalfonso** [comment]
already merged in cms-sw

**Pull request closed without merging**
