### PR TITLE
Add packed jet info for T1 MET re-correction

### PR DESCRIPTION
**Pull request by peruzzim**
first attempt at #326, but some functionality still missing - do not merge

### CODE REVIEW

**Comment by arizzi** [comment]
is there a pt cut? 
132bytes/ev seems a lot to me.
Is using those jets bringing some real and measurable advantage to the MET correction or is just "in miniaod we do it, let's do the same" ?

**Comment by arizzi** [comment]
ah but they are overlapping with the actual Jets??

**Comment by peruzzim** [comment]
yes, this is a work-in-progress, the overlap is 100%

**Comment by arizzi** [comment]
so removing it it would mean storing 6 instead of 16 jets, i.e. the size would be around 40bytes/ev

**Comment by peruzzim** [comment]
will reopen as a clean PR

**Pull request closed without merging**
