### PR TITLE
Adding substructure variables to subjets, needed for JMAR and searches

### PR DESCRIPTION
**Pull request by rappoccio**
The tau1-4 + ECF N2 and N3 variables are already in miniAOD for the subjets. We need them for JMAR characterization as well as searches that want to look inside the W jet.

### CODE REVIEW

**Comment by rappoccio** [comment]
Forgot customizations. 

However, for 92x, I'm getting errors:

```
----- Begin Fatal Exception 03-Nov-2017 14:20:12 CDT-----------------------
An exception of category 'Configuration' occurred while
   [0] Constructing the EventProcessor
   [1] Validating configuration of module: class=PATMuonUpdater label='slimmedMuonsUpdated'
Exception Message:
Illegal parameters found in configuration.  The parameters are named:
 'computeMiniIso'
 'miniIsoParams'
 'pfCandsForMiniIso'
You could be trying to use parameter names that are not
allowed for this plugin or they could be misspelled.
----- End Fatal Exception -------------------------------------------------
```

**Comment by rappoccio** [comment]
Is this failure in the 80x workflow?

**Comment by arizzi** [comment]
yes
An exception of category 'UnknownUserFloat' occurred while
   [0] Processing  Event run: 283877 lumi: 3 event: 3629214 stream: 0
   [1] Running path 'nanoAOD_step'
   [2] Calling method for module
SimpleCandidateFlatTableProducer/'subJetTable'
Exception Message:
Requested UserFloat NjettinessAK8Subjets:tau1 is not available! Possible
UserFloats are:
----- End Fatal Exception -------------------------------------------------

**Comment by rappoccio** [comment]
Ahh, yes, I see now, it was tough to read because the test logs are serial. Got it. 

Will submit a fix in a few minutes.

**Comment by rappoccio** [comment]
Hmm, still getting this error:

```
----- Begin Fatal Exception 06-Nov-2017 09:36:43 CST-----------------------
An exception of category 'Configuration' occurred while
   [0] Constructing the EventProcessor
   [1] Validating configuration of module: class=PATMuonUpdater label='slimmedMuonsUpdated'
Exception Message:
Illegal parameters found in configuration.  The parameters are named:
 'computeMiniIso'
 'miniIsoParams'
 'pfCandsForMiniIso'
You could be trying to use parameter names that are not
allowed for this plugin or they could be misspelled.
----- End Fatal Exception -------------------------------------------------
```

**Comment by arizzi** [comment]
how do you get that? i.e. running what? On the master we do not see such error (neither on the other PRs we just integrated)

**Comment by rappoccio** [comment]
I just rebased my branch onto the nano AOD master (I just pushed the changes) then ran:

```
cmsDriver.py test80X -s NANO --mc --eventcontent NANOAODSIM --datatier NANO --filein /store/relval/CMSSW_8_0_0/RelValTTbar_13/MINIAODSIM/PU25ns_80X_mcRun2_asymptotic_v4-v1/10000/A65CD249-BFDA-E511-813A-0025905A6066.root    --conditions auto:run2_mc -n 100 --era Run2_2016,run2_miniAOD_80XLegacy 
```

**Comment by arizzi** [comment]
Hi,
800 relval are typically broken for Tau. Perhaps not just for tau.
Can you try using for example:
/store/mc/RunIISummer16MiniAODv2/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/MINIAODSIM/PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6_ext1-v2/120000/02A210D6-F5C3-E611-B570-008CFA197BD4.root

**Comment by rappoccio** [comment]
Hmmm, still no.

**Comment by arizzi** [comment]
are you sure you compiled everything?
actually it seems some mismatching config/producer... we should see it
everywhere

**Comment by rappoccio** [comment]
I can start everything from scratch to see if there are any mistakes.

**Comment by arizzi** [comment]
I tried again on my area and
a) I do not get your failure
b) I get the tau failure using your 800 file
c) it works with the file I suggested

**Comment by rappoccio** [comment]
Hm okay, should be a local problem then. Does my latest commit help? I just turned all the substructure variables off again for the subjets (I don't think they were stored in 80x).

**Comment by arizzi** [comment]
@rappoccio can you fix the dqm file?

**Comment by rappoccio** [comment]
OK done.

**Pull request merged**
