### PR TITLE
Updating `triggerObjects_cff.py` to include physics based HLT trigger filter bit scheme

### PR DESCRIPTION
**Pull request by rdewanje**
In this PR, we have changed the HLT filter bit matching logic for the electron, muon and tau objects to be based on easy to understand Physics requirements (e.g. condition on object multiplicity at event level) instead of the requirements based on object IDs (e.g. Isolation WPs etc..) which are less transparent to people outside the Trigger community.

### CODE REVIEW

**Comment by arizzi** [comment]
is the new "base" equivalent ? (i.e. does it cover the same possible use cases covered by the previous one? or are there, for example, multiple paths for single object triggers with different quality cuts that are now missing?)

**Comment by tstreble** [comment]
The new version is not equivalent to the old one.
For instance, the new version assumes for the ele+tau trigger filters
`4*max(filter('hltEle*FilterForTau'),max(filter('hltOverlapFilterIsoEle*PFTau*'),filter('*PFTau*L1HLTMatched')))`
while before there was a larger flexibility since any combination of quality requirements could be required for the filters.
`-	    qualityBits = cms.string("filter('*LooseChargedIso*')+2*filter('*MediumChargedIso*')+4*filter('*TightChargedIso*')+8*filter('*TightOOSCPhotons*')+16*filter('hltL2TauIsoFilter')+32*filter('*OverlapFilterIsoMu*')+64*filter('*OverlapFilterIsoEle*')+128*filter('*L1HLTMatched*')+256*filter('*Dz02*')"), qualityBitsDoc = cms.string("1 = LooseChargedIso, 2 = MediumChargedIso, 4 = TightChargedIso, 8 = TightID OOSC photons, 16 = L2p5 pixel iso, 32 = OverlapFilter IsoMu, 64 = OverlapFilter IsoEle, 128 = L1-HLT matched, 256 = Dz"),            
`
At the moment, we use for instance the loose isolation WP for the ele+tau paths but in case we have to switch to use the medium WP to keep the rates under control, the new implementation does not allow to select only the events triggering the Medium WP but only the OR of all the isolation WPs.
In general, the new implementation is implemented from the perspective of a physics analysis on a dataset already on tape and does not accommodate well changing data-taking conditions for a dataset being recorded.

**Comment by rdewanje** [comment]
I just uploaded the latest version of the 'triggerObjects_cff.py' file incorporating the changes suggested by tstreble . Please go through it and suggest changes (if any). FYI the latest HLT bit masks for e, mu and tau now contain both the old (ID based) as well as the new (physics based) logic in them.

**Comment by rdewanje** [comment]
Is there anything else that needs to be done before this PR can be merged to the master ?

**Comment by arizzi** [comment]
we are good

**Pull request merged**
