### PR TITLE
adding METSigInputProducer to calc sumPt

### PR DESCRIPTION
**Pull request by llechner**
#### PR description:

Adding METSignificanceInputProducer to calculate sumPt (float) to be able to recalculate MET significance on NanoAOD

#### PR validation:

The producer has been tested on CMSSW 10_2_9 and CMSSW_11_0_0_pre10. The output was validated in producing nanoAOD samples for DYJetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8 using Autumn18 conditions. The config for nanoAOD production was produced using:

myNanoProdMc -s NANO --mc --eventcontent NANOAODSIM --datatier NANOAODSIM --no_exec --conditions 102X_upgrade2018_realistic_v12 --era Run2_2018,run2_nanoAOD_102Xv1

All cmssw PR checks passed

### CODE REVIEW

**Comment by peruzzim** [comment]
Checking the code, I understand that it's duplicating the calculation of candidate pt sums, that must already be in place somewhere else in CMSSW.
I don't think this is suitable for inclusion in PhysicsTools/NanoAOD, it should be integrated in the proper folders under JME control with a pull request to the upstream repository first, or you should switch to using an already existing module.

@ahinzmann @lathomas

**Comment by ahinzmann** [comment]
We have related code that runs on AOD in RecoMET/METProducers, however, nothing this is the first piece of code that runs on MiniAOD.
So the next step is to make this PR in CMSSW and find an appropriate place in there?

**Comment by peruzzim** [comment]
yes, please do so

**Comment by ahinzmann** [comment]
@llechner Can you make a PR in CMSSW then, where METSignificanceInputProducer.cc is placed in RecoMET/METProducers?

**Comment by llechner** [comment]
yes, I can do that, thanks

**Comment by danbarto** [comment]
@ahinzmann @peruzzim there is RecoMET/METAlgorithms/src/METSignificance.cc which basically does the same (and a little more as it also calculates the significance itself), however, so far the sumPt value isn't kept. I can open a PR in CMSSW with the necessary changes.

**Comment by ahinzmann** [comment]
@danbarto The best way to implement would be to adapt the existing METSingfincance module to write out the sumPt value (such that we can also store it in MiniAOD). And then we have a simple translation of that value into NanoAOD

**Comment by peruzzim** [comment]
Will have to be redone with only NanoAOD configuration changes, once #28370 is merged and backported where needed. I close this PR for the moment.

**Pull request closed without merging**
