### PR TITLE
Nano aod genparts status flags

### PR DESCRIPTION
**Pull request by l-cadamuro**
Adds the values of the genparticles statusFlags() (a set of 15 bools) stored bitwise as an int.

### CODE REVIEW

**Comment by arizzi** [comment]
@l-cadamuro it is nto exactly cheap in term of size (1% of the total), can you clarify the planned usage for that? do we really need it for all particles or we can restrict to a subset?

**Comment by gpetruc** [comment]
I'm not too concerned about the 1% size, but I think it would be good to understand if this info is eventualy used to compute something rather standard (e.g. study ISR systematics, or gen origin of a reco object), as in that case it may be more convenient to run the algorithm during nanoAOD production, for many reasons independent of disk space:
- to make the analysis on nanoAOD faster, as a loop over all genParticles will be slow.
- to avoid potential issues with loss of precision wrt miniAOD and dropped intermediate particles.
- to help standardize such definitions across analyses

For example, for reco leptons we already have information about the flavour origin of the matched gen particle, and the event already contains standard information for gen-level top quarks and dressed leptons.

**Comment by l-cadamuro** [comment]
The way I used this in the past is to unambiguously identify the particles for signal reweighting (where I need to know who is the first copy to get ME info) and definition of object selection criteria (e.g., know if the selected reco object matches what I want to select, there I want the last copy).

It's sometimes a more useful information than gen jets.
Example: in a HH event, to know that I am picking up the pair of objects from the same H decay and not from the other one. Here flavor origin is not enough as I also need to know the specific H that decayed.

Also particularly useful for taus where the status codes from PYTHIA may vary depending e.g. on the radiation, while isFirstCopy/isLastCopy/isDirectTauDecayProduct etc. are straightforward.

@arizzi Could be dropped for gen mesons and baryons in the final state. Then I don't know if these could also have their use case nor the impact in size reduction.

**Comment by arizzi** [comment]
@gpetruc I guess we can merge and then figure if some further reduction is possible but saving on the hadron is minor as most of the genpart we store are leptons, quarks and vector bosons (in their N copies).

The reduction on number of flag is probably a minor effect as we are already after compression down to 4bits per object... if someone is willing to make tests for futher reduction we can keep this open, otherwise I propose we merge.

**Pull request merged**
