### PR TITLE
New MVA-based anti-e Tau-Id

### PR DESCRIPTION
**Pull request by mbluj**
This PR adds MVA-based anti-e Tau-Id with a new training performed using 2017 samples, as announced in #275. 
This PR is prepared on top of 10_2_8 and cms-sw#25487 which contain no-NanoAOD related ingredients required by the new anti-e tau-Id (+ other stuff introduced between 10_2_6 and 10_2_8). 
Developments introduced by this PR were successfully tested with 1 thread running(*).

(*) NanoAOD with multithread running crashes probably due to Rivet plugin, see #277.

### CODE REVIEW

**Comment by peruzzim** [comment]
@mbluj could you please rebase your updates on top of master-102X?
Is it good to go on top of 10_2_10?

**Comment by mbluj** [comment]
OK, I'll do. Could you, please, specify a target date?

**Comment by mbluj** [comment]
Updated and it looks that conflicts are solved as expected.
Basic tests on top on MiniAODv2 of 2017 data with 94X and MiniAOD of 2018 data with 102X passed (modulo the issue with multi-threaded running with Higgs samples).

**Comment by peruzzim** [comment]
the new variables do not appear in 2016 80X samples - does that correspond to the intentions?

**Comment by mbluj** [comment]
> the new variables do not appear in 2016 80X samples - does that correspond to the intentions?

Yes, the new variables (anti-e TauID with WPs) are meant for 2016 samples rereco'ed with 94X, 2017 samples with 94X and 2018 samples with 102X (and UL samples). Tau POG is not providing updates for 80X based TauIDs.

**Comment by peruzzim** [comment]
@mbluj could you please rebase this on top of master-cmsswmaster (based on 10_6_0_pre3 at the moment) and open a PR to forward port it?
There are some conflicts in the rebase that I would prefer not to fix myself. It would be nice if you could avoid commits changing back-and-forth stuff outside of PhysicsTools/NanoAOD. Thanks

**Comment by mbluj** [comment]
Could you please provide me estimate of deadline? I am not sure if I will be able to work on this before Easter.
Concerning your other comment: what do you mean by changing back-and-forth stuff outside of PhysicsTools/NanoAOD? I do not see anything like this in this PR. However, it could be that I miss something in the history of this PR which has been stalled for long time.

**Comment by peruzzim** [comment]
Forget about my comments, it can be rebased cleanly going through 10_2_10 that already includes some of the commits. Exactly as you say, the history was not very clean.

**Pull request merged**
