### PR TITLE
Simplify pat jet constituent access in 94X

### PR DESCRIPTION
**Pull request by ahinzmann**
Identical to #23007 for testing NanoAOD

### CODE REVIEW

**Comment by gpetruc** [comment]
from past experience the bot can't test PRs that need recompiling Fireworks.
One possibility is to remove the file from the sparse checkout and git
read-tree -mu HEAD before the build in
https://gitlab.cern.ch/cms-nanoAOD/nanoAOD-integration/blob/master/scripts/get_pr.sh#L5

**Comment by arizzi** [comment]
I think there is also a way to avoid the dependecy with merge-topic -u  (or
something like that)

**Comment by arizzi** [comment]
I modified (with -u) the pr_161 branch in gitlab and rerun the pipeline let see.

**Comment by arizzi** [comment]
mhh it seems with -u it did not recompile enough stuff...

trying removing only Fireworks (with a dumb rm -rf)

**Comment by slava77** [comment]
I was hoping to get a reasonably quick confirmation here.
It looks like making a healthy build is problematic with the nano CI

**Comment by arizzi** [comment]
it seems gitlab has limits on the time it should take to make a CI job and this PR need to rebuild a lot of dependencies (because of the changes in the base class).
What we could do is to merge in 10_2_X if it is fine on your side and then we will do the nano testing starting from an IB containing the changes

**Comment by slava77** [comment]
On 4/20/18 7:13 AM, arizzi wrote:
> it seems gitlab has limits on the time it should take to make a CI job
> and this PR need to rebuild a lot of dependencies (because of the
> changes in the base class).

is this timeout a configurable parameter?

> What we could do is to merge in 10_2_X if it is fine on your side and
> then we will do the nano testing starting from an IB containing the changes
> 

OK. I'm waiting for @fabiocos to respond comment or merge the cms-sw
master PR

**Comment by arizzi** [comment]
@slava77 no clue, I just see that it failed with
"ERROR: Job failed: execution took longer than 1h0m0s seconds"

@gpetruc  may know if he set that somewhere when setting it up...

**Pull request closed without merging**
