### PR TITLE
Add pointing angle for SVs

### PR DESCRIPTION
**Pull request by gpetruc**
creating a new PR, mostly to test integration scripts, but will eventually address #18

### CODE REVIEW

**Comment by gpetruc** [comment]
Test started, see https://gitlab.cern.ch/cms-nanoAOD/nanoAOD-integration/-/jobs/616352.

**Comment by gpetruc** [comment]
[](url)

**Comment by arizzi** [comment]
I cannot see the gitlab project

**Comment by gpetruc** [comment]
Automatic test complete, see /pipelines//builds

**Comment by arizzi** [comment]
can we merge this?

**Pull request merged**
