### PR TITLE
DeepTauID to Nano at 102X (2nd try)

### PR DESCRIPTION
**Pull request by mbluj**
#### PR description:

This PR adds DeepTauID to NanoAOD for 102X. This is 2nd try, now on top of 10_2_6, which supersedes #382.

DeepTauID variables in tauTable are defined as in #27226 & #27227, but the DeepTauID is computed within the nanoAOD workflow (instead of being read from MiniAOD). This addition is **not active** for any of already defined NanoAOD eras, namely `run2_miniAOD_80XLegacy`, `run2_nanoAOD_94XMiniAODv1`, `run2_nanoAOD_94X2016`, `run2_nanoAOD_94XMiniAODv2`, `run2_nanoAOD_102Xv1`. Should it be protected by a dedicated era?

The PR is build on top of CMSSW_10_2_16_UL.

#### PR validation:

Validated with nanoAOD workflow obtained with the following cmsDriver command which corresponds with NanoAODv5:
```
cmsDriver.py RunIIFall17NanoAODv5 --filein /store/mc/RunIIFall17MiniAODv2/TTToHadronic_TuneCP5_13TeV-powheg-pythia8/MINIAODSIM/PU2017_12Apr2018_94X_mc2017_realistic_v14-v1/40000/A256C80D-0943-E811-998E-7CD30AB0522C.root --fileout file:RunIIFall17NanoAODv5.root --mc --eventcontent NANOAODSIM --datatier NANOAODSIM --conditions auto:phase1_2017_realistic --step NANO --nThreads 2 --era Run2_2017,run2_nanoAOD_102Xv1 --no_exec -n 1000
```
as well as with its version without `run2_nanoAOD_102Xv1` era specifier.

#### if this PR is a backport please specify the original PR:

This PR can be seen as expanded backport of #27226

### CODE REVIEW

**Comment by mbluj** [comment]
Could you remind be how to get DQM patch, please? When I try use provided link I am ending on "404 page not found".
Regardless, I suppose that there is not a real issue with the nano-DQM. This PR adds new variables to be monitored by nano-DQM, but the variables are not produced for historic eras. For instance log of "Test Simple" suggests that this test is run with the "run2_nanoAOD_102Xv1" era and basing on it a removal of the newly-added variables from nano-DQM is proposed.

**Comment by peruzzim** [comment]
Please remove the DQM update from here, it would pop up for every future PR.
Also, something we might want to add is the possibility to switch on the calculation of deepTau on older files, as some people will need it. Could you please introduce this? Yes, you can use a modifier, or prepare a function that can be called by a customise command.

**Comment by mbluj** [comment]
Adding a new era is fine with me. Any suggestion concerning its name?

**Comment by steggema** [comment]
@peruzzim @fgolf Would be great if you could respond to Michal's question. Merging this would simplify the recipe for users to run DeepTauv2 in their own NanoAOD production workflows.

(FYI @rmanzoni @swozniewski)

**Comment by peruzzim** [comment]
In the interest of having this finally merged, please just remove the DQM update and let's forget about the era modifier. I can add it back in a separate PR, when deciding what to turn on by default e.g. for the next nanoAOD round.

**Comment by mbluj** [comment]
Hi @peruzzim
I'm catching up after my holiday break: do I understand correctly that you have already applied required fix , i.e. removal of the variables added to DQM, so no further action from our side is expected?

**Comment by mbluj** [comment]
Hello,
please also note this DeepTauID-related PR to official CMSSW #27879. The PR contains a fix which is intended to reduce disagreement between data and MC (especially for 2017) and thus reduce scale factors. The fix should be part of Tau-POG-recommented workflow of DeepTauID.

**Comment by peruzzim** [comment]
@mbluj nothing else is needed here, we merge this and will follow up on modifiers and cms-sw#27879 in a separate place

**Pull request merged**
