### PR TITLE
add track met

### PR DESCRIPTION
**Pull request by arizzi**

### CODE REVIEW

**Comment by arizzi** [comment]
should solve #10

**Comment by gpetruc** [comment]
MET naming convention is also messed up, we have
 * `MET_pt`
 * `METCalo_pt` (uppercase C)
 * `METpuppi_pt` (lowercase p)
 *  `MET_genPt`
 * `TkMET_pt` (prefix)
==> maybe we could clean it up into 'MET', 'GenMET', 'CaloMET', 'PuppiMET' ?

**Comment by gpetruc** [comment]
I did some cleanup of the names, @arizzi check if you want and then merge.

**Comment by arizzi** [comment]
seems fine... do you want to merge with the PR open on this branch?

**Comment by gpetruc** [comment]
to sync track met with #20655

**Comment by arizzi** [comment]
I'd sync once the PR is merged and a pre is available. In addition we would need the current definition to go in the legacy Eras

**Pull request merged**
